language: go
go:
  - '1.8'
  - '1.9'
  - 1.10.x

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
#  - go test -v -cover
  - $HOME/gopath/bin/goveralls -v -service=travis-ci
