language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  #  - go test -v -cover
  - $HOME/gopath/bin/goveralls -v -service=travis-ci
