name: Unit-Tests
on:
  pull_request:
    paths:
      - 'go.mod'
      - '**.go'
      - '**.yml'
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - '**.yml'

# https://github.com/actions
jobs:

  test:
    name: Test on go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.18, 1.19, '1.20']

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Display Env
        run: |
          git remote -v
          git tag -l
          env

      - name: Setup Go Faster
        uses: WillAbides/setup-go-faster@v1.10.1
        timeout-minutes: 3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Revive check
        uses: docker://morphy/revive-action:v2.3.1
        with:
          # Exclude patterns, separated by semicolons (optional)
          exclude: "./internal/..."

      - name: Run static check
        uses: reviewdog/action-staticcheck@v1
        if: ${{ github.event_name == 'pull_request'}}
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-check
          # Report all results. [added,diff_context,file,nofilter].
          filter_mode: added
          # Exit with 1 when it find at least one finding.
          fail_on_error: true

      - name: Run tests
        run: |
          pwd
          go test -v -cover ./...
#        go run ./cmd/chlog last head
